### ISSUE TITLE
Markdown Highlighting

### ISSUE THREAD

**Issue by bcomnes** [Riari/tron-legacy-atom#2]
It seems like highlighting markdown isn't as compressive with torn-legacy as other themes:
e.g.

![](https://farm9.staticflickr.com/8898/17616113490_1d6aea1480_o.png)

**Comment by Riari** [comment]
I need to take a look at some other themes that handle this properly as I'm not sure how it's done, but it's on my list.

**Comment by bcomnes** [comment]
I'll post back with hints or PRs if I have time.
