### ISSUE TITLE
Deprecated selector in `tron-legacy/index.less`

### ISSUE THREAD

**Issue by Esaud17** [Riari/tron-legacy-atom#3]
In `tron-legacy/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host,
atom-text-editor` => `atom-text-editor,
atom-text-editor`

* `:host .gutter,
atom-text-editor .gutter` => `atom-text-editor .gutter,
atom-text-editor .gutter`

* `:host .gutter .line-number.cursor-line,
atom-text-editor .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,
atom-text-editor .gutter .line-number.cursor-line`

* `:host .gutter .line-number.cursor-line-no-selection,
atom-text-editor .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,
atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `:host .wrap-guide,
atom-text-editor .wrap-guide` => `atom-text-editor .wrap-guide,
atom-text-editor .wrap-guide`

* `:host .indent-guide,
atom-text-editor .indent-guide` => `atom-text-editor .indent-guide,
atom-text-editor .indent-guide`

* `:host .invisible-character,
atom-text-editor .invisible-character` => `atom-text-editor .invisible-character,
atom-text-editor .invisible-character`

* `:host .search-results .marker .region,
atom-text-editor .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,
atom-text-editor .search-results .syntax--marker .region`

* `:host .search-results .marker.current-result .region,
atom-text-editor .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,
atom-text-editor .search-results .syntax--marker.current-result .region`

* `:host .selection .region,
atom-text-editor .selection .region` => `atom-text-editor .selection .region,
atom-text-editor .selection .region`

* `:host.is-focused .cursor,
atom-text-editor.is-focused .cursor` => `atom-text-editor.is-focused .cursor,
atom-text-editor.is-focused .cursor`

* `:host.is-focused .line-number.cursor-line,
atom-text-editor.is-focused .line-number.cursor-line,
:host.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line-number.cursor-line-no-selection` => `atom-text-editor.is-focused .line-number.cursor-line,
atom-text-editor.is-focused .line-number.cursor-line,atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line-number.cursor-line-no-selection`

* `.comment` => `.syntax--comment`

* `.string` => `.syntax--string`

* `.constant.numeric` => `.syntax--constant.syntax--numeric`

* `.constant.language` => `.syntax--constant.syntax--language`

* `.constant.character,
.constant.other` => `.syntax--constant.syntax--character,
.syntax--constant.syntax--other`

* `.variable` => `.syntax--variable`

* `.keyword` => `.syntax--keyword`

* `.storage` => `.syntax--storage`

* `.storage.type` => `.syntax--storage.syntax--type`

* `.entity.name.class` => `.syntax--entity.syntax--name.syntax--class`

* `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`

* `.entity.name.function` => `.syntax--entity.syntax--name.syntax--function`

* `.variable.parameter` => `.syntax--variable.syntax--parameter`

* `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

* `.support.function` => `.syntax--support.syntax--function`

* `.support.constant` => `.syntax--support.syntax--constant`

* `.support.type,
.support.class` => `.syntax--support.syntax--type,
.syntax--support.syntax--class`

* `.invalid` => `.syntax--invalid`

* `.invalid.deprecated` => `.syntax--invalid.syntax--deprecated`

* `.meta.structure.dictionary.json .string.quoted.double.json` => `.syntax--meta.syntax--structure.syntax--dictionary.syntax--json .syntax--string.syntax--quoted.syntax--double.syntax--json`

* `.meta.diff,
.meta.diff.header` => `.syntax--meta.syntax--diff,
.syntax--meta.syntax--diff.syntax--header`

* `.markup.deleted` => `.syntax--markup.syntax--deleted`

* `.markup.inserted` => `.syntax--markup.syntax--inserted`

* `.markup.changed` => `.syntax--markup.syntax--changed`

* `.constant.numeric.line-number.find-in-files:not(.match)` => `.syntax--constant.syntax--numeric.line-number.syntax--find-in-files:not(.match)`

* `.entity.name.filename.find-in-files` => `.syntax--entity.syntax--name.syntax--filename.syntax--find-in-files`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by jango-fx** [comment]
having the same issue with
- Atom 1.22.1
- tron-legacy v0.5.0


> Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
> 
> :host, atom-text-editor => atom-text-editor, atom-text-editor
> :host .gutter, atom-text-editor .gutter => atom-text-editor .gutter, atom-text-editor .gutter
> :host .gutter .line-number.cursor-line, atom-text-editor .gutter .line-number.cursor-line => atom-text-editor .gutter .line-number.cursor-line, atom-text-editor .gutter .line-number.cursor-line
> :host .gutter .line-number.cursor-line-no-selection, atom-text-editor .gutter .line-number.cursor-line-no-selection => atom-text-editor .gutter .line-number.cursor-line-no-selection, atom-text-editor .gutter .line-number.cursor-line-no-selection
> :host .wrap-guide, atom-text-editor .wrap-guide => atom-text-editor .wrap-guide, atom-text-editor .wrap-guide
> :host .indent-guide, atom-text-editor .indent-guide => atom-text-editor .indent-guide, atom-text-editor .indent-guide
> :host .invisible-character, atom-text-editor .invisible-character => atom-text-editor .invisible-character, atom-text-editor .invisible-character
> :host .search-results .marker .region, atom-text-editor .search-results .marker .region => atom-text-editor .search-results .syntax--marker .region, atom-text-editor .search-results .syntax--marker .region
> :host .search-results .marker.current-result .region, atom-text-editor .search-results .marker.current-result .region => atom-text-editor .search-results .syntax--marker.current-result .region, atom-text-editor .search-results .syntax--marker.current-result .region
> :host .selection .region, atom-text-editor .selection .region => atom-text-editor .selection .region, atom-text-editor .selection .region
> :host.is-focused .cursor, atom-text-editor.is-focused .cursor => atom-text-editor.is-focused .cursor, atom-text-editor.is-focused .cursor
> :host.is-focused .line-number.cursor-line, atom-text-editor.is-focused .line-number.cursor-line, :host.is-focused .line-number.cursor-line-no-selection, atom-text-editor.is-focused .line-number.cursor-line-no-selection => atom-text-editor.is-focused .line-number.cursor-line, atom-text-editor.is-focused .line-number.cursor-line,atom-text-editor.is-focused .line-number.cursor-line-no-selection, atom-text-editor.is-focused .line-number.cursor-line-no-selection
> .comment => .syntax--comment
> .string => .syntax--string
> .constant.numeric => .syntax--constant.syntax--numeric
> .constant.language => .syntax--constant.syntax--language
> .constant.character, .constant.other => .syntax--constant.syntax--character, .syntax--constant.syntax--other
> .variable => .syntax--variable
> .keyword => .syntax--keyword
> .storage => .syntax--storage
> .storage.type => .syntax--storage.syntax--type
> .entity.name.class => .syntax--entity.syntax--name.syntax--class
> .entity.other.inherited-class => .syntax--entity.syntax--other.syntax--inherited-class
> .entity.name.function => .syntax--entity.syntax--name.syntax--function
> .variable.parameter => .syntax--variable.syntax--parameter
> .entity.name.tag => .syntax--entity.syntax--name.syntax--tag
> .entity.other.attribute-name => .syntax--entity.syntax--other.syntax--attribute-name
> .support.function => .syntax--support.syntax--function
> .support.constant => .syntax--support.syntax--constant
> .support.type, .support.class => .syntax--support.syntax--type, .syntax--support.syntax--class
> .invalid => .syntax--invalid
> .invalid.deprecated => .syntax--invalid.syntax--deprecated
> .meta.structure.dictionary.json .string.quoted.double.json => .syntax--meta.syntax--structure.syntax--dictionary.syntax--json .syntax--string.syntax--quoted.syntax--double.syntax--json
> .meta.diff, .meta.diff.header => .syntax--meta.syntax--diff, .syntax--meta.syntax--diff.syntax--header
> .markup.deleted => .syntax--markup.syntax--deleted
> .markup.inserted => .syntax--markup.syntax--inserted
> .markup.changed => .syntax--markup.syntax--changed
> .constant.numeric.line-number.find-in-files:not(.match) => .syntax--constant.syntax--numeric.line-number.syntax--find-in-files:not(.match)
> .entity.name.filename.find-in-files => .syntax--entity.syntax--name.syntax--filename.syntax--find-in-files
